# frozen_string_literal: true

require File.expand_path('../../test_helper', __FILE__)

# The repositories route reaches the converters through RepositoriesController#entry,
# which validates the asset name itself (not in a before_action).
class RepositoriesMoreAssetTest < Redmine::ControllerTest
  include RedmineMorePreviews::TestHelper
  tests RepositoriesController

  fixtures :users, :email_addresses, :projects, :roles, :members, :member_roles,
           :enabled_modules, :repositories

  PRJ_ID = 3

  def setup
    super
    User.current = nil
    @old_enabled_scm = Setting.enabled_scm.dup
    Setting.enabled_scm = @old_enabled_scm + ['Filesystem'] unless @old_enabled_scm.include?('Filesystem')
    @old_settings = Setting.plugin_redmine_more_previews
    Setting.plugin_redmine_more_previews = ZIPPY_SETTINGS
    EnabledModule.create!(project_id: PRJ_ID, name: 'redmine_more_previews')

    @repo_dir = Dir.mktmpdir('rmp-fs-repo')
    build_zip(File.join(@repo_dir, 'a.zip'), 'dir/' => '', 'dir/file.txt' => 'hello', '../../escaped.txt' => 'owned')
    @repository = Repository::Filesystem.create!(project: Project.find(PRJ_ID), url: @repo_dir, path_encoding: '')

    @storage = Dir.mktmpdir('rmp-storage')
    @old_storage = RedmineMorePreviews::Constants::Defaults::MORE_PREVIEWS_STORAGE_PATH
    RedmineMorePreviews::Constants::Defaults.send(:remove_const, :MORE_PREVIEWS_STORAGE_PATH)
    RedmineMorePreviews::Constants::Defaults.const_set(:MORE_PREVIEWS_STORAGE_PATH, @storage)
    @request.session[:user_id] = 1 # admin
  end

  def teardown
    super
    Setting.enabled_scm = @old_enabled_scm
    Setting.plugin_redmine_more_previews = @old_settings
    Setting.clear_cache # the writer caches the symbol key; the plugin reads the string key
    RedmineMorePreviews::Constants::Defaults.send(:remove_const, :MORE_PREVIEWS_STORAGE_PATH)
    RedmineMorePreviews::Constants::Defaults.const_set(:MORE_PREVIEWS_STORAGE_PATH, @old_storage)
    FileUtils.rm_rf(@storage)
    FileUtils.rm_rf(@repo_dir)
  end

  def entry_params(extra = {})
    {id: PRJ_ID, repository_id: @repository.id, path: repository_path_hash(['a.zip'])[:param]}.merge(extra)
  end

  # the listing is generated by the repositories preview route; its links must lead
  # back to the same route (not to the attachments one) and resolve the entry
  def test_toc_link_of_a_nested_entry_resolves_to_the_entry
    get :more_preview, params: entry_params(format: 'html')
    assert_response :success
    href = CGI.unescapeHTML(response.body[/href="([^"]*asset=[^"]*)"/, 1].to_s)
    assert_match %r{\A/projects/#{PRJ_ID}/repository/#{@repository.id}/preview/}, href
    uri = URI.parse(href)
    route = Rails.application.routes.recognize_path(uri.path, method: :get)
    assert_equal 'repositories', route[:controller]
    get route[:action], params: route.except(:controller, :action).merge(Rack::Utils.parse_query(uri.query).symbolize_keys)
    assert_response :success
    assert_equal 'hello', response.body
  end

  # the entry is not on disk in the controller: the download decision (CSP and
  # iframe) is made on its content, like the conversion
  def test_download_sandbox_flag_follows_the_content_not_the_extension
    Setting.plugin_redmine_more_previews = ZIPPY_SETTINGS.deep_merge(
      'converter' => {'pass' => {'active' => '1', 'mime_types' => {'html' => {'active' => '1', 'format' => 'html'}}}}
    )
    Setting.clear_cache
    File.write(File.join(@repo_dir, 'spoof.zip'), '<!DOCTYPE html><html><body>not an archive</body></html>')
    @repository.fetch_changesets

    get :more_preview, params: entry_params(format: 'html')
    assert_response :success
    assert_match(/\Asandbox allow-downloads; /, response.headers['Content-Security-Policy'].to_s)
    get :entry, params: entry_params
    assert_response :success
    assert_select 'iframe[sandbox="allow-downloads"]'

    spoof = entry_params(path: repository_path_hash(['spoof.zip'])[:param])
    get :more_preview, params: spoof.merge(format: 'html')
    assert_response :success
    assert_match(/\Asandbox; /, response.headers['Content-Security-Policy'].to_s)
    get :entry, params: spoof
    assert_response :success
    assert_select 'iframe[sandbox=""]'
  end

  # the bytes are read once and shared by the CSP decision and the conversion
  def test_preview_reads_the_entry_once
    bytes = File.binread(File.join(@repo_dir, 'a.zip'))
    Repository::Filesystem.any_instance.expects(:cat).once.returns(bytes)
    get :more_preview, params: entry_params(format: 'html', reload: 1)
    assert_response :success
    assert_match(/\Asandbox allow-downloads; /, response.headers['Content-Security-Policy'].to_s)
    assert_includes response.body, 'file.txt'
  end

  # the entry page reads the entry for the download decision only when the
  # preview is the sandboxed html one; an inline listing is read by the conversion alone
  def test_inline_entry_page_does_not_read_the_entry_for_the_download_decision
    settings = ZIPPY_SETTINGS.deep_dup
    settings['converter']['zippy']['mime_types']['zip']['format'] = 'inline'
    Setting.plugin_redmine_more_previews = settings
    Setting.clear_cache
    bytes = File.binread(File.join(@repo_dir, 'a.zip'))
    Repository::Filesystem.any_instance.expects(:cat).once.returns(bytes)
    get :entry, params: entry_params(format: 'html')
    assert_response :success
    assert_includes response.body, 'file.txt'
  end

  def test_regular_entry_is_served
    get :entry, params: entry_params(asset: 'dir/file.txt')
    assert_response :success
    assert_equal 'hello', response.body
  end

  def test_unsafe_asset_is_rejected_with_404_not_500
    ['../../escaped.txt', '/etc/hostname', 'dir/../../x.txt'].each do |asset|
      get :entry, params: entry_params(asset: asset)
      assert_response :not_found, asset
    end
    assert_empty Dir.glob(File.join(@storage, '**', 'escaped.txt'))
  end

  def test_missing_entry_is_answered_with_404
    get :entry, params: entry_params(asset: 'nope.txt')
    assert_response :not_found
  end
end
